### ISSUE TITLE
Debuffs not properly being removed from players

### ISSUE THREAD

**Issue by badhex** [badhex/imud-issues#120]
As seen in the logs:
2017-05-19 19:34:59,854 DEBUG COMBAT; round; 114
2017-05-19 19:35:00,640 DEBUG buff; destroy; char; Kazun; type; debuff; icon; front-teeth.png; uuid; 0245932c-ea59-4f55-8fbe-e73385894856
2017-05-19 19:35:00,673 DEBUG buff; destroy; char; Kazun; type; debuff; icon; front-teeth.png; uuid; a76203d0-cf2d-4ae5-822f-55e50a6a6952
2017-05-19 19:35:05,870 DEBUG COMBAT; round; 115
2017-05-19 19:35:06,787 DEBUG buff; destroy; char; Kazun; type; debuff; icon; front-teeth.png; uuid; 7d099473-2e1b-4269-85be-b5cf0e3dcba7
2017-05-19 19:35:11,891 DEBUG COMBAT; round; 116
2017-05-19 19:35:12,942 DEBUG buff; destroy; char; Kazun; type; debuff; icon; front-teeth.png; uuid; 7297bec8-48b5-43bf-b394-bfd8d4928cab
2017-05-19 19:35:17,920 DEBUG COMBAT; round; 117
2017-05-19 19:35:23,945 DEBUG COMBAT; round; 118
2017-05-19 19:35:25,158 DEBUG buff; destroy; char; Kazun; type; debuff; icon; front-teeth.png; uuid; 7584d53e-dbbe-4b86-b2ad-fa50fff59eac
2017-05-19 19:35:29,949 DEBUG COMBAT; round; 119
2017-05-19 19:35:35,976 DEBUG COMBAT; round; 120
2017-05-19 19:35:37,383 DEBUG buff; destroy; char; Kazun; type; debuff; icon; front-teeth.png; uuid; 326e28f9-65b0-4b03-bfe0-0361c19e2eb0
2017-05-19 19:35:41,997 DEBUG COMBAT; round; 121
2017-05-19 19:35:43,598 DEBUG buff; destroy; char; Kazun; type; debuff; icon; front-teeth.png; uuid; e53847b9-4ffc-4cc0-9426-db1739f6a5f4
2017-05-19 19:35:48,018 DEBUG COMBAT; round; 122
2017-05-19 19:35:49,684 DEBUG buff; destroy; char; Kazun; type; debuff; icon; front-teeth.png; uuid; c8c7a521-741c-4840-a55c-7528e6046678
2017-05-19 19:35:54,034 DEBUG COMBAT; round; 123

**Comment by badhex** [comment]
2017-05-19 19:32:41,275 DEBUG buff; create; char; Kazun; seconds; 600; type; debuff; icon; front-teeth.png; uuid; 6dc64ef5-728c-4
ad7-b42e-bb07a854a75d
2017-05-19 19:32:41,312 ERROR COMBAT; doCombatEffect; error; Traceback (most recent call last):
  File "/home/ec2-user/imud/imud_combat.py", line 475, in doCombatEffect
    newbuff = buff(target, esecs, "debuff", eff.name, eff.icon, eff.stackable, eff.id)
  File "/home/ec2-user/imud/imud_types.py", line 1332, in __init__
    eff.event.notify()
AttributeError: '_Event' object has no attribute 'notify'

**Comment by badhex** [comment]
Fixed in: https://github.com/badhex/imud/commit/e7cb74a3fe9194573e73456a6e987ccfc47ba607
